// docs/plans/evidence/bun-views/fviews/solid/Catalog.tsx
// Solid's JSX compiles to templates (babel-preset-solid), not to calls of a
// JSX runtime, so this file goes through the adapter's Babel plugin.
import { For, Show, Suspense, createResource } from "solid-js";
import type { Item } from "../data";

function Card(props: { item: Item }) {
  return (
    <article class="card" data-id={props.item.id}>
      <h2 class="card-title">{props.item.name}</h2>
      <p class="price">${props.item.price.toFixed(2)}</p>
      <p class="desc">{props.item.description}</p>
      <ul class="tags"><For each={props.item.tags}>{(tag) => <li>{tag}</li>}</For></ul>
      <span class="rating" aria-label={`${props.item.rating} stars`}>{"★".repeat(props.item.rating)}</span>
      <button type="button" class="add">Add to cart</button>
    </article>
  );
}

function Recs(props: { promise: Promise<string[]> }) {
  const [list] = createResource(() => props.promise);
  return <aside id="recs"><ul><For each={list()}>{(n) => <li>{n}</li>}</For></ul></aside>;
}

export interface CatalogProps { title: string; items: Item[]; recommendations?: Promise<string[]> }

export default function Catalog(props: CatalogProps) {
  return (
    <div id="page">
      <header><h1>{props.title}</h1><nav><ul><For each={Array.from({ length: 12 }, (_, i) => i)}>{(i) => <li><a href={`/section/${i}`}>Section {i}</a></li>}</For></ul></nav></header>
      <main><For each={props.items}>{(item) => <Card item={item} />}</For></main>
      <Show when={props.recommendations}>
        {(p) => <Suspense fallback={<p id="recs-loading">Loading recommendations…</p>}><Recs promise={p()} /></Suspense>}
      </Show>
      <footer><p>© Example Shop</p></footer>
    </div>
  );
}

// docs/plans/evidence/bun-views/fviews/preact/Catalog.tsx
/** @jsxImportSource preact */
// Preact reads the JSX runtime from the pragma; Bun honours it per file.
import { Suspense, lazy } from "preact/compat";
import type { Item } from "../data";

function Card({ item }: { item: Item }) {
  return (
    <article class="card" data-id={item.id}>
      <h2 class="card-title">{item.name}</h2>
      <p class="price">${item.price.toFixed(2)}</p>
      <p class="desc">{item.description}</p>
      <ul class="tags">{item.tags.map((tag) => <li key={tag}>{tag}</li>)}</ul>
      <span class="rating" aria-label={`${item.rating} stars`}>{"★".repeat(item.rating)}</span>
      <button type="button" class="add">Add to cart</button>
    </article>
  );
}

export interface CatalogProps { title: string; items: Item[]; recommendations?: Promise<string[]> }

export default function Catalog({ title, items, recommendations }: CatalogProps) {
  // preact/compat's lazy() suspends until the promise settles.
  const Recs = recommendations
    ? lazy(async () => {
        const list = await recommendations;
        return { default: () => <aside id="recs"><ul>{list.map((n) => <li key={n}>{n}</li>)}</ul></aside> };
      })
    : null;
  return (
    <div id="page">
      <header><h1>{title}</h1><nav><ul>{Array.from({ length: 12 }, (_, i) => <li key={i}><a href={`/section/${i}`}>Section {i}</a></li>)}</ul></nav></header>
      <main>{items.map((item) => <Card key={item.id} item={item} />)}</main>
      {Recs ? <Suspense fallback={<p id="recs-loading">Loading recommendations…</p>}><Recs /></Suspense> : null}
      <footer><p>© Example Shop</p></footer>
    </div>
  );
}
