// docs/plans/evidence/bun-views/fviews/solid/Counter.tsx
import { createSignal, onMount } from "solid-js";
export interface CounterProps { title: string; start: number; evil: string }
export default function Counter(props: CounterProps) {
  const [count, setCount] = createSignal(props.start);
  const [hydrated, setHydrated] = createSignal(false);
  onMount(() => setHydrated(true));
  return (
    <main data-hydrated={hydrated() ? "yes" : "no"}>
      <p id="evil">{props.evil}</p>
      <button type="button" onClick={() => setCount((n) => n + 1)}>count {count()}</button>
    </main>
  );
}

// docs/plans/evidence/bun-views/fviews/preact/Counter.tsx
/** @jsxImportSource preact */
import { useEffect, useState } from "preact/hooks";
export interface CounterProps { title: string; start: number; evil: string }
export default function Counter({ start, evil }: CounterProps) {
  const [count, setCount] = useState(start);
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => setHydrated(true), []);
  return (
    <main data-hydrated={hydrated ? "yes" : "no"}>
      <p id="evil">{evil}</p>
      <button type="button" onClick={() => setCount((n) => n + 1)}>count {count}</button>
    </main>
  );
}
