// docs/plans/evidence/bun-views/fviews/vue/Catalog.vue
<script setup lang="ts">
import type { Item } from "../data";
import Card from "./Card.vue";
import Recs from "./Recs.vue";
defineProps<{ title: string; items: Item[]; recommendations?: Promise<string[]> }>();
</script>
<template>
  <Teleport to="head"><title>{{ title }}</title></Teleport>
  <div id="page">
    <header><h1>{{ title }}</h1><nav><ul><li v-for="i in 12" :key="i"><a :href="`/section/${i - 1}`">Section {{ i - 1 }}</a></li></ul></nav></header>
    <main><Card v-for="item in items" :key="item.id" :item="item" /></main>
    <Suspense v-if="recommendations">
      <Recs :promise="recommendations" />
      <template #fallback><p id="recs-loading">Loading recommendations…</p></template>
    </Suspense>
    <footer><p>© Example Shop</p></footer>
  </div>
</template>

// docs/plans/evidence/bun-views/fviews/svelte/Catalog.svelte
<script lang="ts">
  import type { Item } from "../data";
  import Card from "./Card.svelte";
  let { title, items, recommendations }: { title: string; items: Item[]; recommendations?: Promise<string[]> } = $props();
</script>
<svelte:head><title>{title}</title></svelte:head>
<div id="page">
  <header><h1>{title}</h1><nav><ul>{#each Array.from({ length: 12 }, (_, i) => i) as i (i)}<li><a href={`/section/${i}`}>Section {i}</a></li>{/each}</ul></nav></header>
  <main>{#each items as item (item.id)}<Card {item} />{/each}</main>
  {#if recommendations}
    {#await recommendations}
      <p id="recs-loading">Loading recommendations…</p>
    {:then list}
      <aside id="recs"><ul>{#each list as n (n)}<li>{n}</li>{/each}</ul></aside>
    {/await}
  {/if}
  <footer><p>© Example Shop</p></footer>
</div>
